### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by johnnyl72** [johnnyl72/LibManage#22]
- [ ]  Create shopping
- [x]  Create option to opt in/out with a footer or account page (not connected to devise) 
- [x]  Add pictures for books and use a default picture if created new book has no image
- [x]  Views for user_status
![image](https://user-images.githubusercontent.com/35053246/68235568-56647400-ffb8-11e9-895e-b89dc9075a57.png)
 - [x]  Views for book index page   
![image](https://user-images.githubusercontent.com/35053246/68235638-7005bb80-ffb8-11e9-8184-5fb1124307c3.png)
- [x]  Views for shelving, returning, check out pages,
![image](https://user-images.githubusercontent.com/35053246/68235521-3df45980-ffb8-11e9-94dc-b645973f8eb4.png)
